
name: Testing Go-Code

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - run: go version    

      - name: Run Linter
        run: make lint
